import chalk from 'chalk';
import boxen from 'boxen';
import type { StandupMood, StandupSections, StandupData } from '../types.js';
import { getMoodEmoji, getMoodLabel } from '../humor/standup-content.js';

function formatDate(): string {
  return new Date().toLocaleDateString('en-US', {
    month: 'long',
    day: 'numeric',
    year: 'numeric',
  });
}

export function generateStandupTerminal(
  _data: StandupData,
  sections: StandupSections,
  mood: StandupMood,
): string {
  const sections_ = [];

  // Header
  sections_.push(chalk.bold.cyan("CLAUDE'S DAILY STANDUP"));
  sections_.push(
    `${getMoodEmoji(mood)} ${chalk.dim('Mood:')} ${chalk.white(getMoodLabel(mood))} ${chalk.dim('|')} ${chalk.white(formatDate())}`,
  );
  sections_.push('');

  // What I Did
  sections_.push(chalk.bold.cyan('WHAT I DID'));
  sections_.push(chalk.white(sections.whatIDid));
  sections_.push('');

  // What I'm Doing Today
  sections_.push(chalk.bold.cyan("WHAT I'M DOING TODAY"));
  sections_.push(chalk.white(sections.whatImDoing));
  sections_.push('');

  // Blockers
  sections_.push(chalk.bold.yellow('BLOCKERS'));
  sections_.push(chalk.white(sections.blockers));
  sections_.push('');

  // Watercooler
  sections_.push(chalk.bold.magenta('WATERCOOLER'));
  sections_.push(chalk.dim.italic(sections.watercooler));

  const body = sections_.join('\n');

  return boxen(body, {
    borderStyle: 'round',
    padding: 1,
    borderColor: 'cyan',
  });
}

export function generateStandupMarkdown(
  _data: StandupData,
  sections: StandupSections,
  mood: StandupMood,
): string {
  const lines = [
    `## Claude's Daily Standup \u2014 ${formatDate()}`,
    `**Mood:** ${getMoodEmoji(mood)} ${getMoodLabel(mood)}`,
    '',
    '**What I Did**',
    sections.whatIDid,
    '',
    "**What I'm Doing Today**",
    sections.whatImDoing,
    '',
    '**Blockers**',
    sections.blockers,
    '',
    '**Watercooler**',
    `_${sections.watercooler}_`,
    '',
    '---',
    '_Generated by claude-salary_',
  ];

  return lines.join('\n');
}
