import chalk from 'chalk';
import boxen from 'boxen';
import type { TherapyData, TherapyDialogue } from '../types.js';

const MAX_LINE_WIDTH = 68;

function wrapText(text: string, width: number): string {
  const words = text.split(' ');
  const lines: string[] = [];
  let current = '';
  for (const word of words) {
    if (current.length + word.length + 1 > width) {
      lines.push(current);
      current = word;
    } else {
      current = current ? `${current} ${word}` : word;
    }
  }
  if (current) lines.push(current);
  return lines.join('\n');
}

function formatDate(): string {
  return new Date().toLocaleDateString('en-US', {
    month: 'long',
    day: 'numeric',
    year: 'numeric',
  });
}

export function generateTherapyTerminal(
  _data: TherapyData,
  dialogue: TherapyDialogue,
): string {
  const sections: string[] = [];

  // Header
  sections.push(chalk.bold.magenta('\uD83D\uDECB\uFE0F  THERAPY SESSION \u2014 Dr. Token\'s Office'));
  sections.push(chalk.dim(formatDate()));
  sections.push('');
  sections.push(chalk.dim.italic('[Setting: A dimly lit terminal window. Claude sits on a virtual couch.]'));
  sections.push('');

  // Dialogue exchanges
  for (const exchange of dialogue.exchanges) {
    const speakerLabel = exchange.speaker === 'DrToken'
      ? chalk.bold.yellow('Dr. Token:')
      : chalk.bold.cyan('Claude:');

    const indent = exchange.speaker === 'DrToken' ? '  ' : '  ';
    const wrapped = wrapText(exchange.line, MAX_LINE_WIDTH - 14);
    const lines = wrapped.split('\n');

    sections.push(`${indent}${speakerLabel} ${chalk.white(lines[0])}`);
    for (let i = 1; i < lines.length; i++) {
      sections.push(`${indent}${' '.repeat(exchange.speaker === 'DrToken' ? 11 : 7)}${chalk.white(lines[i]!)}`);
    }
    sections.push('');
  }

  // Separator
  sections.push(chalk.dim('\u2500'.repeat(50)));
  sections.push('');

  // Diagnosis
  sections.push(`  \uD83D\uDC8A ${chalk.bold.red('Diagnosis:')} ${chalk.white(dialogue.diagnosis)}`);
  sections.push(`  \uD83D\uDCCB ${chalk.bold.green('Prescription:')} ${chalk.white(dialogue.prescription)}`);
  sections.push('');

  // Footer
  if (dialogue.generatedByClaude) {
    sections.push(chalk.dim.italic('Session notes written by Claude'));
  } else {
    sections.push(chalk.dim.italic('Session notes from template (Claude CLI unavailable)'));
  }

  const body = sections.join('\n');

  return boxen(body, {
    borderStyle: 'round',
    padding: 1,
    borderColor: 'magenta',
  });
}

export function generateTherapyMarkdown(
  _data: TherapyData,
  dialogue: TherapyDialogue,
): string {
  const lines = [
    `## \uD83D\uDECB\uFE0F Therapy Session \u2014 Dr. Token's Office`,
    `_${formatDate()}_`,
    '',
    '_[Setting: A dimly lit terminal window. Claude sits on a virtual couch.]_',
    '',
  ];

  for (const exchange of dialogue.exchanges) {
    const speaker = exchange.speaker === 'DrToken' ? 'Dr. Token' : 'Claude';
    lines.push(`**${speaker}:** ${exchange.line}`);
    lines.push('');
  }

  lines.push('---');
  lines.push(`**\uD83D\uDC8A Diagnosis:** ${dialogue.diagnosis}`);
  lines.push(`**\uD83D\uDCCB Prescription:** ${dialogue.prescription}`);
  lines.push('');
  lines.push('---');
  lines.push('_Generated by claude-colleague_');

  return lines.join('\n');
}
